{
 "title": "NiceHash Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Miners mining",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "minersmining" }
   ]
  },
  {
   "title": "BTC balance",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "btcbalance" }
   ]
  },
  {
   "title": "BTC Unpaid",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "btcunpaid" }
   ]
  },
  {
   "title": "Estimated time until withdraw",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "limitreach" }
   ]
  },
  {
   "title": "Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    { "expr": "sum(hashrate)", "legendFormat": "Accepted:" },
    { "expr": "sum(hashrejected)", "legendFormat": "Rejected:" }
   ]
  },
  {
   "title": "Profitability per 24/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "sum(profitability)", "legendFormat": "Actual:" },
    { "expr": "sum(localprofitability)", "legendFormat": "Local:" }
   ]
  },
  { "title": "Miners", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Hashrate Per Miner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    { "expr": "hashrate", "legendFormat": "{{rigname}}:" }
   ]
  },
  {
   "title": "Rejected Hashrate Per Miner",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "MHs" } },
   "targets": [
    { "expr": "hashrejected", "legendFormat": "{{rigname}} Rejected" }
   ]
  },
  {
   "title": "Profitability per miner 24/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "profitability", "legendFormat": "{{rigname}}:" }
   ]
  },
  {
   "title": "Local profitability per miner 24/h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "targets": [
    { "expr": "localprofitability", "legendFormat": "{{rigname}} Local" }
   ]
  }
 ]
}